### ISSUE TITLE
"the type mining-tool has been obsoleted and cannot be created" when crafting manasteel axe

### ISSUE THREAD

**Issue by jonoh2** [KorGgenT/Thaumaturgic-Machinations#64]
When you attempt to craft a manasteel axe, it returns this error message and kicks you back to the main menu.
can the item be removed, or changed?

i have not played thaumaturgic machinations yet, so i do not know if this item is of importance.

I am Jonathan_1205# 0758 on discord btw

**Comment by Danielv123** [comment]
Afaik it was only a way to increase the mining speed over the steel axe, but that feature was removed from the base game. I am surprised it doesn't error during loading the mod rather than at runtime.

It can be safely removed. If a crafting speed increase is a feature we feel like we need to have it should be hidden behind a research instead.

**Comment by jonoh2** [comment]
ok cool
